services:
  portfolio-site:
    image: ghcr.io/annisa-rachma/annisarachma.com:v.1.1
    platform: linux/amd64
    container_name: portfolio-site
    ports:
      - "8080:80"
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - portfolio-site
    networks:
      - app-network

networks:
  app-network:
