services:
  portfolio:
    image: ghcr.io/annisa-rachma/annisarachma.com:latest
    container_name: portfolio
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`annisarachma.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"

      - "traefik.http.routers.portfolio-http.rule=Host(`annisarachma.com`)"
      - "traefik.http.routers.portfolio-http.entrypoints=web"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"

      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  traefik_network:
    external: true