services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/acme.json:/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.annisarachma.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
    networks:
      - web

  app:
    image: ghcr.io/annisa-rachma/annisarachma.com:latest
    container_name: portfolio-app
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`annisarachma.com`)"
      - "traefik.http.routers.react.entrypoints=websecure"
      - "traefik.http.routers.react.tls.certresolver=letsencrypt"
      - "traefik.http.services.react.loadbalancer.server.port=8080"

networks:
  web:
    driver: bridge
    