services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=saa.annisa15@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: ghcr.io/annisa-rachma/annisarachma.com:latest
    container_name: portfolio-app
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.guestbook.rule=Host(`annisarachma.com`)"
        - "traefik.http.routers.guestbook.entrypoints=websecure"
        - "traefik.http.routers.guestbook.tls.certresolver=myresolver"
        
        # Middleware: redirect HTTP -> HTTPS
        #- "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
